version: '3.4'

services:
  th_loginserver:
    image: ${DOCKER_REGISTRY-}thloginserver
    build:
      context: .
      dockerfile: TH_LoginServer/Dockerfile
    ports:
    - "9901:80"
    depends_on:
    - "redis_image"
    links:
    - "redis_image"

  redis_image:
    image: redis:alpine
    container_name: RedisDB
    ports:
      - "6379:6379"